### ISSUE TITLE
Display cost of running assays

### ISSUE THREAD

**Issue by OliviaSimpson** [SABS-Group-2-2021-22/drug-discovery-game-app#156]
It would be nice to know how much in game budget will be spent when you click run assays on the assay page.
It could work by dynamically changing the run assay button, but other solutions such as a new visual element that looks like an invoice could be good

**Comment by guydurant** [comment]
Isn't it already in the game?

**Comment by arunraja-hub** [comment]
WIP https://github.com/SABS-Group-2-2021-22/drug-discovery-game-app/tree/156-display-cost-assay

**Comment by arunraja-hub** [comment]
Completed and merged: https://github.com/SABS-Group-2-2021-22/drug-discovery-game-app/commit/6f35ad4aaba1ae8c7afb037343614b91f5ddfb7e
