### ISSUE TITLE
Add links to explain features 

### ISSUE THREAD

**Issue by adpunt** [SABS-Group-2-2021-22/drug-discovery-game-app#286]
logD: https://www.cambridgemedchemconsulting.com/resources/physiochem/logD.html
PAMPA: https://en.wikipedia.org/wiki/Parallel_artificial_membrane_permeability_assay 
Clearance: https://en.wikipedia.org/wiki/Clearance_(pharmacology) 
pIC50: https://www.collaborativedrug.com/what-is-pic50-2/#:~:text=Simply%20stated%2C%20pIC50%20is%20the,is%20a%20pIC50%20of%209
https://en.wikipedia.org/wiki/IC50
MMP12: https://en.wikipedia.org/wiki/Matrix_metallopeptidase_12
logP: https://en.wikipedia.org/wiki/Partition_coefficient#Partition_coefficient_and_log_P 
TPSA: https://en.wikipedia.org/wiki/Polar_surface_area 
Heavy atom: non-hydrogen atom
Hydrogen bonding: https://en.wikipedia.org/wiki/Hydrogen_bond
ADMET: https://en.wikipedia.org/wiki/ADME 
Lipinski’s: https://en.wikipedia.org/wiki/Lipinski%27s_rule_of_five#cite_note-Lipinski_2001-1

**Comment by TomKWise** [comment]
Links added
